# Generated by Django 5.0.2 on 2024-02-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
